### ISSUE TITLE
PhoneGap Windows

### ISSUE THREAD

**Issue by pankajvk** [davejohnson/phonegap-windows#2]
I have downloaded phoneGap windows source code and added webkit.net reference.
but It gives build error like

Error   1   Source file 'E:\Project Rewind\Open Source code\davejohnson-phonegap-windows-e0f5de7\davejohnson-phonegap-windows-e0f5de7\tools\TypeNormalizer.cs' could not be found   E:\Project Rewind\Open Source code\davejohnson-phonegap-windows-e0f5de7\WebKit.NET-0.5-src\WebKitBrowser\EXEC   WebKitBrowser

WebKit.Net download version 0.5

Please help me out 

Thanks

**Comment by davejohnson** [comment]
I haven't heard of that error and havent really tried the code in quite a while! we might be resurrecting this soon though so stay tuned!

**Comment by pankajvk** [comment]
Hi Dave,

Thanks for reply.

I got the missing file from WebKit.Net Source code.Now Its build successfully.
But I got error at runtime as 

File not found exception for WebViewClass.
Retrieving the COM class factory for component with CLSID {D6BCA079-F61C-4E1E-B453-32A0477D02E3} failed due to the following error: 8007007e.

I tried to find in source code but it looks like its getting referenced from metadata DLL/Temp folder.

Please help me out

With Thanks and Regards,
Pankaj K
