### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by frengom** [davejohnson/phonegap-windows#5]
Hello, I imported the project in Visual C# 2010 Express, fixed the reference, and tried to build several times but I am still not able to get your project to work. Since I'm a newbie in Visual Studio, can you please provide a more detailed guide about how to setup the environment? The main error is related to the method InvokeScript of Webkit.WebKitBrowser, which seems to be not existing. I used Cairo's .dll. Thanks.

**Comment by krazyjakee** [comment]
Hi I have the same issue but with VC# 2008.
Any update on this?

**Comment by frengom** [comment]
Unfortunately still nothing... Since it was just for a demo I didn't insist on this approach, it seems that the author dropped this project since he's not updating it for 2 years and not answering here...

**Comment by krazyjakee** [comment]
Damn, well I discovered webkitdotnet so I think I'm good to go.
